# https://hub.docker.com/r/bitnami/solr
# https://docs.platform.sh/guides/drupal9/solr.html
# /opt/bitnami/solr/server/solr/dafe-d10

version: '2'

services:
  solr-node1:
    image: docker.io/bitnami/solr:8
    environment:
      - SOLR_ENABLE_AUTHENTICATION=no
      - SOLR_CORE_CONF_DIR=/data/search_api_solr_4
      - SOLR_CORES=dafe-d10
    volumes:
      - ./solr_drupal_config:/data/search_api_solr_4
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_solr.rule=Host(`${PROJECT_BASE_URL}`)"
  traefik:
    image: traefik:v2.9
    container_name: "${PROJECT_NAME}_traefik"
    command: 
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker
    ports:
    - "81:80"
    - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock